name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Download SwiftLint latest (macOS)
      shell: bash
      run: |
        mkdir download && cd download
        wget https://github.com/realm/SwiftLint/releases/latest/download/portable_swiftlint.zip
        unzip portable_swiftlint.zip
        echo SWIFTLINT_BINARY="$(pwd -L)/swiftlint" >> $GITHUB_ENV
      working-directory: ${{ github.action_path }}

    - name: Lint
      run: $SWIFTLINT_BINARY
